services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./test-api
      dockerfile: Dockerfile
    container_name: nest_api
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "3001:3001"
    depends_on:
      - db

  webapp:
    build:
      context: ./test-webapp
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3001
        VITE_PORT : 3000 
    container_name: react_webapp   
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data: